---
title: "M&SFA"
author: "Bouke"
date: "9/25/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
df <- read.csv("Speed_Dating_Data.csv")

```

```{r Chapter_1_Introduction}
# In a world where nobody has time ... what does speed dating data reveal about us? 
# Storyline: 
# .. 
# This data set includes ..
# and has been cleaned by taking steps .. 
```

```{r open_dataset}
knitr::opts_chunk$set(echo = TRUE)

dating_frame <- df[, c("samerace", "match", "order", "age_o", "expnum")]
lookfor_frame <- df[, c("pf_o_att", "pf_o_sin", "pf_o_int", "pf_o_fun", "pf_o_amb", "pf_o_sha")]
# race <- df$race
# hist(race)
```

```{r Chapter_2_Descriptive_statistics}
# Setting up the dataset 
dfr <- df[df$wave != 6 | df$wave != 7, ] # We want to exclude waves 6-9 because their scores are different
dating_frame <- df[, c("samerace", "match", "order", "age_o", "expnum")] # select all of the columns we will be investigating in this report 

print(cat("Total sample size of the dataset is ", nrow(dfr), " and the number of variables totals", ncol(dfr)))
 # provide an overview of the nr of observations 

# Gender plot
distribution <- table(dfr$gender) # generate a distribution table of 
slices <- c(distribution[names(distribution) == 0], distribution[names(distribution) == 1]) 
lbls <- c("Male", "Female")
pie(slices, labels = lbls, main = "Pie Chart of Gender")
print(mean(waves$gender)) 

# Age histogram 
print("The sample includes people aging in the range of .. to .. ")
age_hist <- dfr$age
hist(age_hist)

# 

```


```{r project_setup}
knitr::opts_chunk$set(echo = TRUE)

# Question 3: What do we want? (correlation analysis and hypothesis testing)
# Distinguish between male and female 
# Relevant variables: 1) gender; 2) wave (because it shows how points were given); 3) age (own, can be used to see if people of different ages score differently); 4) field_cd: code for degree background, use to identify which backgrounds have certain preferences; 5) race; 6) imprace: how important is it that person is of same race (1-10)?; 7) imprelig: importance of religion; 8) goal; 9) attr1_1, sinc1_1, intel1_1, fun1_1, amb1_1, shar1_1: these state what people look for in the same sex; 10a) attr3_1 for all 5 attributes: how do you think you score on 5 attributes (except shared interest) -> relate condifence level to what we want? can also use 10b) attr5_1 etc. and 10c) expnum; 11) career_c: gives a code for the type of career people pursue (some career typed people might be more interested in people that are ambiitous as well); 12) date: how frequently do you go on a date (1-7), can provide indication of 

# to do in session 3: 1) think of real questions you want to ask to limit the number of variables;  2) list all variables and make a subset; 3) clean the data for your own variables; 4) start analysis phase 


```


```{r Chapter_4: Hypothesis testing}
knitr::opts_chunk$set(echo = TRUE)

# Question 4: Hypothesis - dating changes the preferences of people

library(ggplot2)
library(dplyr)

#What do you look for in the opposite sex - right after speed-dating
#Column names: attr1_2 sinc1_2 intel 1_2 fun1_2 amb1_2 shar1_2 


#action:normalize above variables


#What do you look for in the opposite sex - after possible dating (4w later)
# Column names: attr1_3 sinc1_3 intel1_3 fun1_3 amb1_3 shar1_3 


#action:normalize above variables


# action:get all columns for 1_3, 1_2, date_3
my_eval <- select(df,attr1_2, sinc1_2, intel1_2, fun1_2, amb1_2, shar1_2,attr1_3, sinc1_3, intel1_3, fun1_3, amb1_3, shar1_3, date_3,id)



# Have you been on a date with any of your matches?
# Variable: date_3 Yes=1, No=2

#action:limit one dataset to Yes=1 and one to No=2

had_date <- filter(my_eval,date_3 ==1)

no_date <- filter(my_eval, date_3 == 2)

#action:make column sums for both data sets


#action: plot 1_3 and 1_2 for Yes and plot 1_3 and 1_2 for No - bar chart




```


```{r Chapter_4: Hypothesis testing Marianne}
knitr::opts_chunk$set(echo = TRUE)

# Question 4: Hypothesis - dating changes the preferences of people


#What do you look for in the opposite sex - right after speed-dating
# Column names: attr1_2 sinc1_2 intel 1_2 fun1_2 amb1_2 shar1_2 

#What do you look for in the opposite sex - after possible dating (4w later)
# Column names: attr1_3 sinc1_3 intel1_3 fun1_3 amb1_3 shar1_3 

#action:normalize above variables
originset <- read.csv("Speed_Dating_Data.csv", header = TRUE)
summary(originset)

elements_2 = c("attr1_2", "sinc1_2", "intel1_2", "fun1_2", "amb1_2", "shar1_2")
elements_3 = c("attr1_3", "sinc1_3", "intel1_3", "fun1_3", "amb1_3", "shar1_3")
j = 1
totalrow = dim(originset)[1]

summary(originset[elements_2])  #check that the min and max is correct (clean)
summary(originset[elements_3])  #check that the min and max is correct (clean)

while (j <= totalrow) {  #repeat for each row
  totalscore = 0  #compute total score for each row
  for (i in elements_2){
    totalscore = totalscore + originset[j,i]
  }
  for (i in elements_2){   #compute the normalised score for each elements
    originset[j,i] = originset[j,i] * 100 / totalscore
  }
  for (k in elements_3){
    totalscore = totalscore + originset[j,k]
  }
  for (k in elements_3){   #compute the normalised score for each elements
    originset[j,i] = originset[j,k] * 100 / totalscore
  }  
  j = j + 1
}

# action:get all columns for 1_3, 1_2, date_3

Q4_df <- originset[, c("attr1_2", "sinc1_2", "intel1_2", "fun1_2", "amb1_2", "shar1_2", "attr1_3", "sinc1_3", "intel1_3", "fun1_3", "amb1_3", "shar1_3", "date_3")]


# Have you been on a date with any of your matches?
# Variable: date_3 Yes=1, No=0

#action:limit one dataset to Yes=1 and one to No=0
Q4_df_yes <- subset(Q4_df, date_3 == "1")
Q4_df_no <- subset(Q4_df, date_3 == "0")

#action: plot 1_3 and 1_2 for Yes and plot 1_3 and 1_2 for No
library(ggplot2)


#starting values: not different for sinc, fun and attr
t.test(Q4_df_yes$attr1_2,Q4_df_no$attr1_2,alternative = "two.sided")
t.test(Q4_df_yes$fun1_2,Q4_df_no$fun1_2,alternative = "two.sided")
t.test(Q4_df_yes$shar1_2,Q4_df_no$shar1_2,alternative = "two.sided")
t.test(Q4_df_yes$amb1_2,Q4_df_no$amb1_2,alternative = "two.sided")
t.test(Q4_df_yes$sinc1_2,Q4_df_no$sinc1_2,alternative = "two.sided")
t.test(Q4_df_yes$intel1_2,Q4_df_no$intel1_2,alternative = "two.sided")


#same means: attr,sinc, intel means are different for: pos: fun,shar neg:amb
#since we only had same means to begin with for sinc, fun and attr, there are only changes in intel and fun
#two sided means that the sample mean is different from 0 (checking on both sides of 0)
#if I get a p-value below 0.05, I reject the 0 hypothesis - meaning that the means are different
#if I get a p-value above 0.05, I fail to reject the 0 hypothesis 
t.test(Q4_df_yes$attr1_3,Q4_df_no$attr1_3,alternative = "two.sided")
t.test(Q4_df_yes$fun1_3,Q4_df_no$fun1_3,alternative = "two.sided")
t.test(Q4_df_yes$shar1_3,Q4_df_no$shar1_3,alternative = "two.sided")
t.test(Q4_df_yes$amb1_3,Q4_df_no$amb1_3,alternative = "two.sided")
t.test(Q4_df_yes$sinc1_3,Q4_df_no$sinc1_3,alternative = "two.sided")
t.test(Q4_df_yes$intel1_3,Q4_df_no$intel1_3,alternative = "two.sided")


#for those going on a date: importance of intelligence decreases and importance of fun increases if you went on a date
ggplot(Q4_df,aes(x=fun1_2,y=fun1_3,colour=factor(date_3)))+geom_point(alpha=0.1)+
  geom_smooth(data=Q4_df_no, aes(x=fun1_2, y=fun1_3), color='#FD5A31')+
  geom_smooth(data=Q4_df_yes, aes(x=fun1_2, y=fun1_3), color='#4FCDE1')+
  labs(title = "How important is a fun personality to you?", x = "After speeddating", y = "Four weeks later")+
  scale_colour_discrete(name  ="Dating",
                        breaks=c("0", "1"),
                        labels=c("Have not dated", "Have dated"))


ggplot(Q4_df,aes(x=intel1_2,y=intel1_3,colour=factor(date_3)))+geom_point(alpha=0.1)+
  geom_smooth(data=Q4_df_no, aes(x=intel1_2, y=intel1_3), color='#FD5A31')+
  geom_smooth(data=Q4_df_yes, aes(x=intel1_2, y=intel1_3), color='#4FCDE1')+
  labs(title = "How important is intelligence to you?", x = "After speeddating", y = "Four weeks later")+
  scale_colour_discrete(name  ="Dating",
                        breaks=c("0", "1"),
                        labels=c("Have not dated", "Have dated"))





ggplot(Q4_df_yes, aes(x = attr1_2, y = attr1_3)) + geom_point() + geom_smooth()+
  geom_smooth(data=Q4_df_no, aes(x=attr1_2, y=attr1_3), color='red')+
  labs(title = "How important is attractiveness to you?", x = "After speeddating", y = "Four weeks later")

ggplot(Q4_df_yes, aes(x = sinc1_2, y = sinc1_3),color='green') + geom_point() + geom_smooth()+
  geom_smooth(data=Q4_df_no, aes(x=sinc1_2, y=sinc1_3), color='red')+
  labs(title = "How important is sincerity to you?", x = "After speeddating", y = "Four weeks later")

ggplot(Q4_df_yes, aes(x = intel1_2, y = intel1_3),color='green') + geom_point() + geom_smooth()+
  geom_smooth(data=Q4_df_no, aes(x=intel1_2, y=intel1_3), color='red')+
  labs(title = "How important is intelligence to you?", x = "After speeddating", y = "Four weeks later")

ggplot(Q4_df_yes, aes(x = fun1_2, y = fun1_3),color='green') + geom_point() + geom_smooth()+
  geom_smooth(data=Q4_df_no, aes(x=fun1_2, y=fun1_3), color='red')+
  labs(title = "How important is a fun personality to you?", x = "After speeddating", y = "Four weeks later")

ggplot(Q4_df_yes, aes(x = amb1_2, y = amb1_3),color='green') + geom_point() + geom_smooth()+
  geom_smooth(data=Q4_df_no, aes(x=amb1_2, y=amb1_3), color='red')+
  labs(title = "How important is ambition to you?", x = "After speeddating", y = "Four weeks later")

ggplot(Q4_df_yes, aes(x = shar1_2, y = shar1_3),color='green') + geom_point() + geom_smooth()+
  geom_smooth(data=Q4_df_no, aes(x=shar1_2, y=shar1_3), color='red')+
  labs(title = "How important are shared interests to you?", x = "After speeddating", y = "Four weeks later")

#same means: attr,sinc, intel means are different for: pos: fun,shar neg:amb

```




``` {r}
# Comments: 
# 1. Mention that the dataset is relatively old, and from the US 

# 2: normalize the scores of the different waves to ensure everyone scored a total of 100 points.


